---
name: "Freddy Drennan"
title: "Dplyr and Shiny RMD"
date: "November 25, 2017"
output:
  html_document:
    toc: true
    theme: cerulean
    highlight: haddock
    fig_align: center
runtime: shiny
---


<style>
body {
    background-color: #BCE6FF
}
</style>

<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.9&appId=1440881362667639";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div>

<!-- Footer -->
<header>
<!-- <div class="container"> -->
<div class="row">
<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
<ul class="list-inline text-center">
<li>
<a href="http://fdrennan.net">
<span class="fa-stack fa-lg">
<i class="fa fa-circle fa-stack-2x"></i>
<i class="fa fa-arrow-left fa-stack-1x fa-inverse"></i>
</span>
</a>
</li>
<li>
<a href="mailto:drennanfreddy@gmail.com?Subject=Hello">
<span class="fa-stack fa-lg">
<i class="fa fa-circle fa-stack-2x"></i>
<i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
</span>
</a>
</li>
<li>
<a href="https://www.linkedin.com/in/freddy-drennan-4a8b79aa">
<span class="fa-stack fa-lg">
<i class="fa fa-circle fa-stack-2x"></i>
<i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
</span>
</a>
</li>
<li>
<a href="http://facebook.com/freddy.drennan">
<span class="fa-stack fa-lg">
<i class="fa fa-circle fa-stack-2x"></i>
<i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
</span>
</a>
</li> 
<li>
<a href="http://kaggle.com/fdrennan">
<span class="fa-stack fa-lg">
<i class="fa fa-circle fa-stack-2x"></i>
<i class="fa fa-area-chart fa-stack-1x fa-inverse"></i>
</span>
</a>
</li> 
<li>
<a href="https://github.com/fdrennan">
<span class="fa-stack fa-lg">
<i class="fa fa-circle fa-stack-2x"></i>
<i class="fa fa-github fa-stack-1x fa-inverse"></i>
</span>
</a>
</li>
</ul>
</div>
</div>
</div>
</header>

################################################















Clone working directory with command ```git clone https://github.com/fdrennan/storms.git```

```{r, warning = FALSE, message = FALSE}
rm(list = ls())

library(tidyverse)
library(lubridate)
library(ggmap)
library(ggthemes)
library(shiny)
library(plotly)
```

```{r, warning = FALSE, message = FALSE}
storms <- 
  storms %>% 
  # Joining separate date columns
  unite(
    # Columns to combine
    year, month, day, hour, 
    # New Column Name
    col = "date", 
    # How columns should be separated
    sep = "-"
  ) %>% 
  mutate(
    # Using function from lubridate
    date = ymd_h(date)
  )

cuba <-
  geocode("cuba") %>%
  as.numeric

cuba_map <-
  get_googlemap(center=cuba, scale=2, zoom=3) %>%
  ggmap(., extent="normal")


```

```{r, warning = FALSE, message = FALSE}

shinyApp(
  
  ui = fluidPage(
    dateRangeInput("date", "Date", start = "2014-01-01"),
    plotlyOutput("hurricainePlot")
  ),
  
  server = function(input, output) {
    output$hurricainePlot <- renderPlotly({
      storm_filter <- 
        storms %>% 
        arrange(name, date) %>% 
        filter(
          date > min(input$date),
          date < max(input$date)
        )

    plot_output <- 
    cuba_map + 
      geom_path(
        data = storm_filter,
        aes(x = long, y = lat, colour = name)
      ) +
      theme(legend.position='none')
    
    ggplotly(plot_output, height = 1000) 

    })
  },
  
  
  options = list(height = 1000)
)

```


```{r, warning = FALSE, message = FALSE}
storm_filter <- 
  storms %>% 
  arrange(name, date)

cuba_map + 
  geom_density2d(
    data = storm_filter,
    aes(x = long, y = lat)
  ) 
```


```{r, warning = FALSE, message = FALSE}
storms %>% 
  ggplot() +
  aes(x = wind, y = pressure) +
  geom_density_2d()
```


```{r, warning = FALSE, message = FALSE}
category <- 
storms %>% 
  mutate(
    year = year(date)
  ) %>% 
  group_by(year, category) %>% 
  count() 


ggplot(
  data = category,
  aes(x = year, y = n, colour = category)
) +
  theme_solarized(light = TRUE) +
  stat_smooth(se = FALSE) 
  
```













##############################################
<div>

<!-- Footer -->
<header>
<!-- <div class="container"> -->
<div class="row">
<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
<ul class="list-inline text-center">
<li>
<a href="http://fdrennan.net">
<span class="fa-stack fa-lg">
<i class="fa fa-circle fa-stack-2x"></i>
<i class="fa fa-arrow-left fa-stack-1x fa-inverse"></i>
</span>
</a>
</li>
<li>
<a href="mailto:drennanfreddy@gmail.com?Subject=Hello">
<span class="fa-stack fa-lg">
<i class="fa fa-circle fa-stack-2x"></i>
<i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
</span>
</a>
</li>
<li>
<a href="https://www.linkedin.com/in/freddy-drennan-4a8b79aa">
<span class="fa-stack fa-lg">
<i class="fa fa-circle fa-stack-2x"></i>
<i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
</span>
</a>
</li>
<li>
<a href="http://facebook.com/freddy.drennan">
<span class="fa-stack fa-lg">
<i class="fa fa-circle fa-stack-2x"></i>
<i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
</span>
</a>
</li> 
<li>
<a href="http://kaggle.com/fdrennan">
<span class="fa-stack fa-lg">
<i class="fa fa-circle fa-stack-2x"></i>
<i class="fa fa-area-chart fa-stack-1x fa-inverse"></i>
</span>
</a>
</li> 
<li>
<a href="https://github.com/fdrennan">
<span class="fa-stack fa-lg">
<i class="fa fa-circle fa-stack-2x"></i>
<i class="fa fa-github fa-stack-1x fa-inverse"></i>
</span>
</a>
</li>
</ul>
</div>
</div>
</div>
</header>

<div class="fb-comments" data-href="http://fdrennan.net/pages/pages2/storms.html" data-numposts="5"></div>


